### ISSUE TITLE
Request for Assistance: Bug in Demo of Custom User Model Implementation

### ISSUE THREAD

**Issue by GitIzana** [DevOgabek/DjangoBlogPlatform#1]
Dear DevOgabek,

I hope this message finds you well. I was exploring your repository, and I must say I'm impressed by the work you've done. However, while testing the demo, I encountered an issue related to the custom user model implementation.

Upon attempting to sign up, the following error occurred:

```
AttributeError at /user/signup/
Manager isn't available; 'auth.User' has been swapped for 'user.CustomUser'
```

Given your expertise and attention to detail, I believe this might have slipped past during testing. Would you mind taking a look and addressing this issue? It seems to be a bug in the demo version, possibly related to the custom user model configuration.

Your assistance in resolving this matter would be greatly appreciated. Please let me know if you need any further information or assistance from my side.

Thank you for your attention to this matter.
<img width="1063" alt="Screen Shot 2024-02-24 at 19 17 16" src="https://github.com/DevOgabek/DjangoBlogPlatform/assets/161138109/1e93f876-68db-4493-8f8b-ec2f5f148a21">

**Comment by DevOgabek** [comment]
Dear [GitIzana](https://github.com/GitIzana),

I've resolved the signup issue in the demo by updating the code to integrate our custom user model, CustomUser. Now, users can sign up seamlessly, with improved security measures in place.

Thank you for your patience and feedback. Feel free to reach out with any further issues or suggestions.

Now you can see this message again 😁 
<img width="351" alt="Screen Shot 2024-02-24 at 19 22 24" src="https://github.com/DevOgabek/DjangoBlogPlatform/assets/159776741/ccc99169-7459-49f7-b5ce-ea38c79d7aef">


DevOgabek
